/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file combolock.c
 *
 * @author Christopher A. Bohn
 *
 * @brief Driver code for ComboLock Group Project.
 *
 ******************************************************************************/

/*
 * ComboLock Group Project (c) 2022-24 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */


#include <CowPi.h>
#include "display.h"
#include "rotary-encoder.h"
#include "servomotor.h"
#include "lock-controller.h"

static bool test_mode;

void setup() {
    record_build_timestamp(__FILE__, __DATE__, __TIME__);
    cowpi_setup(0,
                (cowpi_display_module_t) {.display_module = NO_MODULE},
                (cowpi_display_module_protocol_t) {.protocol = NO_PROTOCOL}
               );
    initialize_display(21);
    initialize_rotary_encoder();
    initialize_servo();
    initialize_lock_controller();
    print_build_timestamps(true);
    test_mode = cowpi_right_switch_is_in_left_position();
}

void loop() {
    if (test_mode) {
        static char rotations_buffer[22] = {0};
        static char servo_buffer[22] = {0};
        static char combo_buffer[22] = {0};
        count_rotations(rotations_buffer);
        display_string(1, rotations_buffer);
        test_servo(servo_buffer);
        display_string(2, servo_buffer);
        uint8_t const *combination = get_combination();
        sprintf(combo_buffer, "Combo: %02d-%02d-%02d", combination[0], combination[1], combination[2]);
        display_string(3, combo_buffer);
        static bool is_pressed = false;
        if (cowpi_right_button_is_pressed() && !is_pressed) {
            is_pressed = true;
            force_combination_reset();
        }
        if (!cowpi_right_button_is_pressed() && is_pressed) {
            is_pressed = false;
        }
    } else {
        control_lock();
    }
    refresh_display();
    count_visits(7);
}