/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file rotary-encoder.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Function prototypes and a type definition to report the direction that
 *      the rotary encoder is turning or has turned.
 *
 ******************************************************************************/

/*
 * ComboLock Group Project (c) 2022-24 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef COMBOLOCK_ROTARY_ENCODER_H
#define COMBOLOCK_ROTARY_ENCODER_H

typedef enum {
    STATIONARY, CLOCKWISE, COUNTERCLOCKWISE
} direction_t;

void initialize_rotary_encoder();
uint8_t get_quadrature();
char *count_rotations(char buffer[]);
direction_t get_direction();

#endif //COMBOLOCK_ROTARY_ENCODER_H
