/*                       *
 * DO NOT EDIT THIS FILE *
 *                       */

/**************************************************************************//**
 *
 * @file servomotor.h
 *
 * @author Christopher A. Bohn
 *
 * @brief Function prototypes to direct the behavior of a servomotor.
 *
 ******************************************************************************/

/*
 * ComboLock Group Project (c) 2022-24 Christopher A. Bohn
 *
 * Starter code licensed under the Apache License, Version 2.0
 * (http://www.apache.org/licenses/LICENSE-2.0).
 */

#ifndef COMBOLOCK_SERVOMOTOR_H
#define COMBOLOCK_SERVOMOTOR_H

void initialize_servo();
void center_servo();
void rotate_full_clockwise();
void rotate_full_counterclockwise();
char *test_servo(char buffer[]);

#endif //COMBOLOCK_SERVOMOTOR_H
